;------------------------------------------------------------------------------
; Generates SABOT1.BIN, containing:
; 1. S1BOOT.MAC - code and data
; 2. S1SCRN.LZS - compressed title screen
; 3. S1TILE.LZS - compressed tiles data

; Memory mode register values
;          .___1___...00.00	Page	Purpose
MMODE0 = ^B0001110000000000	; 5:4  -  system
MMOD34 = ^B0011110000000000	; 3:4  -  for loading
MMOD36 = ^B0011111100000000	; 3:6  -  for S1TILE
MMODE1 = ^B0011100000000000	; 3:1  -  main program, no screen
MMODE5 = ^B0001100000000000	; 5:1  -  to draw on the screen
MMOD52 = ^B0001101000000000	; 5:2  -  to draw using Byte2Word tables

; Palette register values
;          ST..____........
;PMODES = ^B0000000000000000	; Screen page 5, palette 0

S1LZS2 = <<S1LZSZ + 1> / 2> * 2		; S2LZSZ aligned to words
START = 001400				; Start address of the main code block

L33124 = 120000				; Table used to extend byte to word

STBOOT:
	MTPS	#340			; disable all interruptions
	MOV	#1330, @#177664		; set standard scroll value
	;MOV	#PMODES, @#177662	; set palette for the title screen
	CLR	@#177662		; screen 5, palette 0, vsync on
; Prepare, unpack, load
	CALL	BOOTP1
; Unpack the main code block
	MOV	#<140000-S1LZS2>, R1	; address from
	MOV	#START, R2		; address to
	CALL	UNLZSA
; Start the main program
	JMP	@#START

;------------------------------------------------------------------------------

; https://github.com/purplesyringa/lzsa3
; Optimized LZSA3 decompressor for PDP-11 by Manwe and Ivanq. Thanks to Ivan Gorodetsky
; Usage: MOV #src_adr,R1 / MOV #dst_adr,R2 / CALL UNLZSA
UNLZSA:
	CLR R5				; no nibbles sign
10$:	MOVB (R1)+,R3			; read token
;Liter:
20$:	MOV R3,R0
	BIC #177774,R0			; get 2 bits
	BEQ 30$
	CMP R0,#3			; literals length
	BNE 25$
	CALL 110$
25$:	MOVB (R1)+,(R2)+		; literals length in R0
	SOB R0,25$
;Decode:
30$:	MOV R3,-(SP)
	ROLB R3				; get 2 bits
	ROL R0
	ROLB R3
	ROL R0
	ASL R0
	ADD R0,PC			; run subroutine
	BR 90$
	BR 70$
	BR 80$
;o5bit:
40$:	CALL 100$			; get nibble in R0
	ROLB R3
	ROL R0
	INC R0
;Save:
50$:	MOV R0,R4			; save offset for future
;Match:
55$:	MOV (SP)+,R0
	ASR R0
	ASR R0
	BIC #177770,R0			; get 3 bits
	CMP R0,#7
	BNE 60$
	CALL 110$
	TSTB R0				; match length
	BEQ 120$
;Clone:
60$:	MOV R2,R3
	SUB R4,R3
	MOVB (R3)+,(R2)+
	INC R0
61$:	MOVB (R3)+,(R2)+
	SOB R0,61$
	BR 10$
;o9bit:
70$:	CLR R0
	BISB (R1)+,R0
	ROLB R3
	ROL R0
	INC R0
	BR 50$
;o13bit:
80$:	CALL 100$ 			; get nibble in R0
	ROLB R3
	ROL R0
	SWAB R0
	BISB (R1)+,R0			; 8 bits
	ADD #513.,R0
	BR 50$
;oOther:
90$:	ROLB R3
	BCS 55$
	BISB (R1)+,R0			; read 16 bits
	SWAB R0
	BISB (R1)+,R0
	BR 50$
;Nibble:
100$:	COM R5
	BMI 101$
	MOV R5,R0
	CLR R5
	BR 102$
101$:	BICB (R1)+,R5			; read 2 nibbles
	MOV R5,R0
	ASR R0
	ASR R0
	ASR R0
	ASR R0
102$:	BIC #177760,R0			; leave 4 low bits
	RETURN
;Extend:
110$:	MOV R0,-(SP)			; save original value
	CALL 100$ 			; get nibble in R0
	BNE 112$
	BISB (R1)+,R0
	BNE 111$
	; unnecessary for short files
	BISB (R1)+,R0			; read high byte
	SWAB R0
	BISB (R1)+,R0			; read low byte
	TST (SP)+			; skip saved R0
	RETURN
111$:	ADD #15.,R0
112$:	DEC R0
	ADD (SP)+,R0			; add original value
;Exit:
120$:	RETURN

;------------------------------------------------------------------------------
;
BOOTP1:
; Text under the title screen
	CLR	R1			; колонка курсора = 0
	MOV	#20., R2		; строка курсора
	EMT	24			; установка курсора в позицию
	MOV	#SLoading, R1
	CLR	R2
	EMT	20			; вывод строки
; Unpack the title screen
	MOV	#LZSCRN, R1		; address from
	MOV	#040000, R2		; address to: screen
	CALL	UNLZSA
; Unpack the compressed S1TILE block into page 6
	MOV	#MMOD36, @#177716	; Включаем режим памяти 3:6
	MOV	#LZTILE, R1		; address from
	MOV	#100000, R2		; address to
	CALL	UNLZSA
; Pre-calculate data
	CALL	PREPARE			; Prepare tables in page 2
; Load the compressed code block
	MOV	#MMOD34, @#177716	; Set memory mode 3:4, to load the code
	MOV	#PBLK1, R1
	CALL	@#120002		; call ANDOS
; Move up the compressed main code block
	MOV	#MMODE1, @#177716	; Set memory mode 1
	MOV	#140000, R2		; Адрес ДО которого перемещаем
	MOV	#<2000+S1LZS2>, R1	; Адрес с которого перемещаем, верхняя граница
	MOV	#<S1LZS2/2>, R3
1$:	MOV	-(R1), -(R2)
	SOB	R3, 1$
;
	RETURN

PBLK1:
	.BYTE	3	; Command 3 = read file
	.BYTE	0	; Answer
	.WORD	2000	; Address
	.WORD	S1LZSZ	; Block size after S1CORE.MAC compilation and compression
	.ASCII	/S1CORE.LZS      /
	.WORD	0
	.WORD	0
	.ASCII	/                /

; String to show on loading
SLoading:
	.BYTE	232	; cursor off
	.BYTE	233	; 32/64
	.ASCII	/original 1985 by Clive Townsend/<12>
	.ASCII	/BK-0011M port by NZeemin/<12>/  /
.INCLUDE /VERSIO.MAC/
;NOTE: S1LZSZ value passed with VERSIO.MAC
	.BYTE	0
	.EVEN

PREPARE:
; Prepare PXCONV table, used to convert pixels BYTE -> BK WORD
	MOV	#MMOD52, @#177716	; Set memory mode
	MOV	#L33124, R2
	MOV	#-128., R3		; R3 runs from -128. to +127.
1$:	CLR	R5			; in R5 will be the word
	MOV	#8., R4			; R4 = bits counter
	MOV	R3, R1
2$:	ASR	R1			; bit 0 goes into C flag
	BCC	5$
	ROL	R5			; get from C flag
	ROL	R5
	BR	8$
5$:	ROL	R5			; get 0 from C flag
	SEC
	ROL	R5
8$:	SOB	R4, 2$			; repeat
	MOV	R5, (R2)+		; write the result
	INC	R3
	CMP	R3, #128.
	BLT	1$
; Prepare byte -> word tables, 16 tables by 512 bytes, see Byte2Word00
	CLR	R5			; xxxxPPII (P-paper, I-ink)
	MOV	#100000, R4
10$:	MOV	R5, 40$+2
	MOV	R5, 50$+2
	BIC	#^B1111111111111100, 40$+2 ; modify bis for 'ink'
	ASR	50$+2			; modify bis for 'paper'
	ASR	50$+2
	MOV	#200, R0		; (!) start conversion from -0 (signed byte)
20$:	CLR	(R4)			; cycle 256 bytes
	MOV	R0, R1
	MOV	#8., R3
30$:	ASL	(R4)			; cycle 8 bits
	ASL	(R4)
	ASLB	R1
	BCC	50$
40$:	BIS	#000000, (R4)		; set 'ink'
	BR	60$
50$:	BIS	#000000, (R4)		; set 'paper'
60$:	SOB	R3, 30$
	INC	R4
	INC	R4
	INCB	R0
	CMPB	#200, R0
	BNE	20$
	INC	R5
	CMP	R5, #16.
	BLO	10$
;
	RETURN

; Сжатый экран
LZSCRN:
.INSERT /S1SCRN.LZS/

; Сжатый блок S1TILE
LZTILE:
.INSERT /S1TILE.LZS/

;------------------------------------------------------------------------------

.SCRIPT "Check BOOTP1"
	MOV	#START, R0
	SUB	#BOOTP1, R0
	BPL	1$
	$type	"PROBLEM: BOOTP1 > START"
1$:
.ENDS

;------------------------------------------------------------------------------

	.END
