;------------------------------------------------------------------------------

; Режимы для регистра управления памятью
;          .___1___...00.00	Стр.	Назначение
MMODE0 = ^B0001110000000000	; 5:4  -  системный
MMOD34 = ^B0011110000000000	; 3:4  -  для загрузки
MMOD36 = ^B0011111100000000	; 3:6  -  для S2TILE
MMODE1 = ^B0011100000000000	; 3:1  -  основной
MMODE5 = ^B0001100000000000	; 5:1  -  для рисования на экране

; Значение регистра управления палитрами для заставки
;          ST..____........
;PMODES = ^B0000000000000000	; Screen page 5, palette 0

S1LZS2 = <<S1LZSZ + 1> / 2> * 2		; S2LZSZ но выровненный до слова
START = 001400				; Start address of the main code block

STBOOT:
	MTPS	#340			; disable all interruptions
	MOV	#1330, @#177664		; set standard scroll value
	;MOV	#PMODES, @#177662	; set palette for the title screen
	CLR	@#177662		; screen 5, palette 0, vsync on
; Prepare, unpack, load
	CALL	BOOTP1
; Unpack the main code block
	MOV	#<140000-S1LZS2>, R1	; address from
	MOV	#START, R2		; address to
	CALL	UNLZSA
; Start the main program
	JMP	@#START

;------------------------------------------------------------------------------

; https://github.com/purplesyringa/lzsa3
; Optimized LZSA3 decompressor for PDP-11 by Manwe and Ivanq. Thanks to Ivan Gorodetsky
; Usage: MOV #src_adr,R1 / MOV #dst_adr,R2 / CALL UNLZSA
UNLZSA:
	CLR R5				; no nibbles sign
10$:	MOVB (R1)+,R3			; read token
;Liter:
20$:	MOV R3,R0
	BIC #177774,R0			; get 2 bits
	BEQ 30$
	CMP R0,#3			; literals length
	BNE 25$
	CALL 110$
25$:	MOVB (R1)+,(R2)+		; literals length in R0
	SOB R0,25$
;Decode:
30$:	MOV R3,-(SP)
	ROLB R3				; get 2 bits
	ROL R0
	ROLB R3
	ROL R0
	ASL R0
	ADD R0,PC			; run subroutine
	BR 90$
	BR 70$
	BR 80$
;o5bit:
40$:	CALL 100$			; get nibble in R0
	ROLB R3
	ROL R0
	INC R0
;Save:
50$:	MOV R0,R4			; save offset for future
;Match:
55$:	MOV (SP)+,R0
	ASR R0
	ASR R0
	BIC #177770,R0			; get 3 bits
	CMP R0,#7
	BNE 60$
	CALL 110$
	TSTB R0				; match length
	BEQ 120$
;Clone:
60$:	MOV R2,R3
	SUB R4,R3
	MOVB (R3)+,(R2)+
	INC R0
61$:	MOVB (R3)+,(R2)+
	SOB R0,61$
	BR 10$
;o9bit:
70$:	CLR R0
	BISB (R1)+,R0
	ROLB R3
	ROL R0
	INC R0
	BR 50$
;o13bit:
80$:	CALL 100$ 			; get nibble in R0
	ROLB R3
	ROL R0
	SWAB R0
	BISB (R1)+,R0			; 8 bits
	ADD #513.,R0
	BR 50$
;oOther:
90$:	ROLB R3
	BCS 55$
	BISB (R1)+,R0			; read 16 bits
	SWAB R0
	BISB (R1)+,R0
	BR 50$
;Nibble:
100$:	COM R5
	BMI 101$
	MOV R5,R0
	CLR R5
	BR 102$
101$:	BICB (R1)+,R5			; read 2 nibbles
	MOV R5,R0
	ASR R0
	ASR R0
	ASR R0
	ASR R0
102$:	BIC #177760,R0			; leave 4 low bits
	RETURN
;Extend:
110$:	MOV R0,-(SP)			; save original value
	CALL 100$ 			; get nibble in R0
	BNE 112$
	BISB (R1)+,R0
	BNE 111$
	; unnecessary for short files
	BISB (R1)+,R0			; read high byte
	SWAB R0
	BISB (R1)+,R0			; read low byte
	TST (SP)+			; skip saved R0
	RETURN
111$:	ADD #15.,R0
112$:	DEC R0
	ADD (SP)+,R0			; add original value
;Exit:
120$:	RETURN

;------------------------------------------------------------------------------
;
BOOTP1:
; Text under the title screen
	CLR	R1			; колонка курсора = 0
	MOV	#20., R2		; строка курсора
	EMT	24			; установка курсора в позицию
	MOV	#SLoading, R1
	CLR	R2
	EMT	20			; вывод строки
; Unpack the title screen
	MOV	#LZSCRN, R1		; address from
	MOV	#040000, R2		; address to: screen
	CALL	UNLZSA
;; Загрузить сжатый блок S1TILE
;	MOV	#MMOD34, @#177716	; Включаем режим памяти 3:4, для загрузки блока
;	MOV	#PBLK2, R1
;	CALL	@#120002		; call ANDOS
; Unpack the compressed S1TILE block into page 6
	MOV	#MMOD36, @#177716	; Включаем режим памяти 3:6
	MOV	#LZTILE, R1		; address from
	MOV	#100000, R2		; address to
	CALL	UNLZSA
; Load the compressed code block
	MOV	#MMOD34, @#177716	; Включаем режим памяти 3:4, для загрузки кода
	MOV	#PBLK1, R1
	CALL	@#120002		; call ANDOS
; Move up the compressed main code block
	MOV	#MMODE1, @#177716	; Включаем режим памяти 1, основной
	MOV	#140000, R2		; Адрес ДО которого перемещаем
	MOV	#<2000+S1LZS2>, R1	; Адрес с которого перемещаем, верхняя граница
	MOV	#<S1LZS2/2>, R3
1$:	MOV	-(R1), -(R2)
	SOB	R3, 1$
;
	RETURN

PBLK1:
	.BYTE	3	; Команда 3 = читать файл
	.BYTE	0	; Ответ
	.WORD	2000	; Адрес
	.WORD	S1LZSZ	; Размер - берём после компиляции S1CORE.MAC
	.ASCII	/S1CORE.LZS      /
	.WORD	0
	.WORD	0
	.ASCII	/                /
;PBLK2:
;	.BYTE	3	; Команда 3 = читать файл
;	.BYTE	0	; Ответ
;	.WORD	3000	; Адрес
;	.WORD	S1TZSZ	; Размер - берём после сжатия
;	.ASCII	/S1TILE.LZS      /
;	.WORD	0
;	.WORD	0
;	.ASCII	/                /

; Строка для вывода при загрузке
SLoading:
	.BYTE	232	; cursor off
	.BYTE	233	; 32/64
	.ASCII	/original 1985 by Clive Townsend/<12>
	.ASCII	/BK-0011M port by NZeemin/<12>/  /
.INCLUDE /VERSIO.MAC/
	.BYTE	0
	.EVEN

; Сжатый экран
LZSCRN:
.INSERT /S1SCRN.LZS/

; Сжатый блок S1TILE
LZTILE:
.INSERT /S1TILE.LZS/

;------------------------------------------------------------------------------

	.END
